name: Test TakuCoinMarketTestAPI
on:
  push:
    branches:
    - master
env:
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 5.6.3
  API_IMPORT_SPECIFICATION_PATH: Taku.CoinMarketTest.API/publish/swagger.json
  API_IMPORT_DLL: Taku.CoinMarketTest.API/bin/Release/net6.0/Taku.CoinMarketTest.API.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: Taku.CoinMarketTest.API

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore dependencies
      run: dotnet restore ${{ env.WORKING_DIRECTORY }}
    - name: Build
      run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }}
    - name: Run tests
      run: dotnet test Taku.CoinMarketTest.UnitTest --configuration ${{ env.CONFIGURATION }} --no-build
